name: Release Project

on:
   push:
      branches:
         - david
      paths:
         - CHANGELOG.md
   workflow_dispatch:

jobs:
   release:
      permissions:
         actions: read
         contents: write
      uses: davidgamero/action-release-workflows/.github/workflows/release_js_project.yaml@david
      with:
         changelogPath: ./CHANGELOG.md
